// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmauzrfpggoowonynaxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtYXV6cmZwZ2dvb3dvbnluYXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4NTQ1NDQsImV4cCI6MjA1MjQzMDU0NH0.TsaM9UPjpw-rJDo1A0b5CP3308CSzMzJobPJZ6i8Tsk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);